#############################################################################
# Makefile for building: ../Debug/FalconBoard
# Generated by qmake (3.1) (Qt 5.15.8)
# Project:  FalconBoard/FalconBoard.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile FalconBoard/FalconBoard.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -std=c++17 -Wno-unused-parameter -Wno-reorder -g -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -IFalconBoard -I. -IFalconBoard -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -IDebug/moc -IDebug/Ui -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = FalconBoard1.0.0
DISTDIR = /win/d/sajat/vegyes/FalconBoard/Debug/FalconBoard1.0.0
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS) -L. /usr/lib/x86_64-linux-gnu/libQt5PrintSupport.so /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Network.so /usr/lib/x86_64-linux-gnu/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = Debug/

####### Files

SOURCES       = FalconBoard/common.cpp \
		FalconBoard/drawables.cpp \
		FalconBoard/DrawArea.cpp \
		FalconBoard/FalconBoard.cpp \
		FalconBoard/history.cpp \
		FalconBoard/main.cpp \
		FalconBoard/myprinter.cpp \
		FalconBoard/pagesetup.cpp \
		FalconBoard/pencolorsdialog.cpp \
		FalconBoard/pencolorset.cpp \
		FalconBoard/rotateinput.cpp \
		FalconBoard/screenshotTransparency.cpp \
		FalconBoard/snipper.cpp Debug/rcc/qrc_FalconBoard.cpp \
		Debug/moc/moc_DrawArea.cpp \
		Debug/moc/moc_FalconBoard.cpp \
		Debug/moc/moc_helpdialog.cpp \
		Debug/moc/moc_pagesetup.cpp \
		Debug/moc/moc_pencolorsdialog.cpp \
		Debug/moc/moc_pencolorset.cpp \
		Debug/moc/moc_printprogress.cpp \
		Debug/moc/moc_rotateinput.cpp \
		Debug/moc/moc_screenshotTransparency.cpp \
		Debug/moc/moc_snipper.cpp
OBJECTS       = Debug/common.o \
		Debug/drawables.o \
		Debug/DrawArea.o \
		Debug/FalconBoard.o \
		Debug/history.o \
		Debug/main.o \
		Debug/myprinter.o \
		Debug/pagesetup.o \
		Debug/pencolorsdialog.o \
		Debug/pencolorset.o \
		Debug/rotateinput.o \
		Debug/screenshotTransparency.o \
		Debug/snipper.o \
		Debug/qrc_FalconBoard.o \
		Debug/moc_DrawArea.o \
		Debug/moc_FalconBoard.o \
		Debug/moc_helpdialog.o \
		Debug/moc_pagesetup.o \
		Debug/moc_pencolorsdialog.o \
		Debug/moc_pencolorset.o \
		Debug/moc_printprogress.o \
		Debug/moc_rotateinput.o \
		Debug/moc_screenshotTransparency.o \
		Debug/moc_snipper.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		FalconBoard/.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		FalconBoard/FalconBoard/FalconBoard.pro FalconBoard/common.h \
		FalconBoard/drawables.h \
		FalconBoard/DrawArea.h \
		FalconBoard/FalconBoard.h \
		FalconBoard/helpdialog.h \
		FalconBoard/history.h \
		FalconBoard/myevent.h \
		FalconBoard/myprinter.h \
		FalconBoard/pagesetup.h \
		FalconBoard/pencolorsdialog.h \
		FalconBoard/pencolorset.h \
		FalconBoard/printprogress.h \
		FalconBoard/quadtree.h \
		FalconBoard/rotateinput.h \
		FalconBoard/screenshotTransparency.h \
		FalconBoard/smoother.h \
		FalconBoard/snipper.h FalconBoard/common.cpp \
		FalconBoard/drawables.cpp \
		FalconBoard/DrawArea.cpp \
		FalconBoard/FalconBoard.cpp \
		FalconBoard/history.cpp \
		FalconBoard/main.cpp \
		FalconBoard/myprinter.cpp \
		FalconBoard/pagesetup.cpp \
		FalconBoard/pencolorsdialog.cpp \
		FalconBoard/pencolorset.cpp \
		FalconBoard/rotateinput.cpp \
		FalconBoard/screenshotTransparency.cpp \
		FalconBoard/snipper.cpp
QMAKE_TARGET  = FalconBoard
DESTDIR       = ../Debug/
TARGET        = ../Debug/FalconBoard


first: all
####### Build rules

../Debug/FalconBoard: Debug/Ui/ui_FalconBoard.h Debug/Ui/ui_helpdialog.h Debug/Ui/ui_pagesetup.h Debug/Ui/ui_pencolorsdialog.h Debug/Ui/ui_pencolorset.h Debug/Ui/ui_printprogress.h Debug/Ui/ui_rotateinput.h Debug/Ui/ui_screenshotTransparency.h $(OBJECTS)  
	@test -d ../Debug/ || mkdir -p ../Debug/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: FalconBoard/FalconBoard.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		FalconBoard/FalconBoard.pro \
		FalconBoard/FalconBoard.qrc
	$(QMAKE) -o Makefile FalconBoard/FalconBoard.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlmodels.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_virtualkeyboard.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
FalconBoard/FalconBoard.pro:
FalconBoard/FalconBoard.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile FalconBoard/FalconBoard.pro

qmake_all: FORCE


all: Makefile ../Debug/FalconBoard

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents FalconBoard/FalconBoard.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents FalconBoard/common.h FalconBoard/drawables.h FalconBoard/DrawArea.h FalconBoard/FalconBoard.h FalconBoard/helpdialog.h FalconBoard/history.h FalconBoard/myevent.h FalconBoard/myprinter.h FalconBoard/pagesetup.h FalconBoard/pencolorsdialog.h FalconBoard/pencolorset.h FalconBoard/printprogress.h FalconBoard/quadtree.h FalconBoard/rotateinput.h FalconBoard/screenshotTransparency.h FalconBoard/smoother.h FalconBoard/snipper.h $(DISTDIR)/
	$(COPY_FILE) --parents FalconBoard/common.cpp FalconBoard/drawables.cpp FalconBoard/DrawArea.cpp FalconBoard/FalconBoard.cpp FalconBoard/history.cpp FalconBoard/main.cpp FalconBoard/myprinter.cpp FalconBoard/pagesetup.cpp FalconBoard/pencolorsdialog.cpp FalconBoard/pencolorset.cpp FalconBoard/rotateinput.cpp FalconBoard/screenshotTransparency.cpp FalconBoard/snipper.cpp $(DISTDIR)/
	$(COPY_FILE) --parents FalconBoard/FalconBoard.ui FalconBoard/helpdialog.ui FalconBoard/pagesetup.ui FalconBoard/pencolorsdialog.ui FalconBoard/pencolorset.ui FalconBoard/printprogress.ui FalconBoard/rotateinput.ui FalconBoard/screenshotTransparency.ui $(DISTDIR)/
	$(COPY_FILE) --parents ../translations/FalconBoard_en.ts ../translations/FalconBoard_hu.ts $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: Debug/rcc/qrc_FalconBoard.cpp
compiler_rcc_clean:
	-$(DEL_FILE) Debug/rcc/qrc_FalconBoard.cpp
Debug/rcc/qrc_FalconBoard.cpp: FalconBoard/FalconBoard.qrc \
		/usr/lib/qt5/bin/rcc \
		translations/FalconBoard_en.qm \
		translations/FalconBoard_hu.qm \
		FalconBoard/Resources/close.png \
		FalconBoard/Resources/save.png \
		FalconBoard/Resources/open.png \
		FalconBoard/Resources/falconboard_ico.png \
		FalconBoard/Resources/undo.png \
		FalconBoard/Resources/screenshot.png \
		FalconBoard/Resources/move.png \
		FalconBoard/Resources/printer.png \
		FalconBoard/Resources/trash-can.png \
		FalconBoard/Resources/redo.png \
		FalconBoard/Resources/multi.png \
		FalconBoard/Resources/saveas.png \
		FalconBoard/Resources/falconboard.png \
		FalconBoard/Resources/white.png \
		FalconBoard/Resources/new.png \
		FalconBoard/Resources/zoomrot.png \
		FalconBoard/Resources/eraser.png
	/usr/lib/qt5/bin/rcc -name FalconBoard FalconBoard/FalconBoard.qrc -o Debug/rcc/qrc_FalconBoard.cpp

compiler_moc_predefs_make_all: Debug/moc/moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) Debug/moc/moc_predefs.h
Debug/moc/moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -std=c++17 -Wno-unused-parameter -Wno-reorder -g -Wall -Wextra -dM -E -o Debug/moc/moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: Debug/moc/moc_DrawArea.cpp Debug/moc/moc_FalconBoard.cpp Debug/moc/moc_helpdialog.cpp Debug/moc/moc_pagesetup.cpp Debug/moc/moc_pencolorsdialog.cpp Debug/moc/moc_pencolorset.cpp Debug/moc/moc_printprogress.cpp Debug/moc/moc_rotateinput.cpp Debug/moc/moc_screenshotTransparency.cpp Debug/moc/moc_snipper.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) Debug/moc/moc_DrawArea.cpp Debug/moc/moc_FalconBoard.cpp Debug/moc/moc_helpdialog.cpp Debug/moc/moc_pagesetup.cpp Debug/moc/moc_pencolorsdialog.cpp Debug/moc/moc_pencolorset.cpp Debug/moc/moc_printprogress.cpp Debug/moc/moc_rotateinput.cpp Debug/moc/moc_screenshotTransparency.cpp Debug/moc/moc_snipper.cpp
Debug/moc/moc_DrawArea.cpp: FalconBoard/DrawArea.h \
		FalconBoard/common.h \
		FalconBoard/drawables.h \
		FalconBoard/config.h \
		FalconBoard/quadtree.h \
		FalconBoard/history.h \
		FalconBoard/pagesetup.h \
		Debug/Ui/ui_pagesetup.h \
		FalconBoard/myprinter.h \
		FalconBoard/myevent.h \
		Debug/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /win/d/sajat/vegyes/FalconBoard/Debug/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/win/d/sajat/vegyes/FalconBoard/FalconBoard -I/win/d/sajat/vegyes/FalconBoard/FalconBoard -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include FalconBoard/DrawArea.h -o Debug/moc/moc_DrawArea.cpp

Debug/moc/moc_FalconBoard.cpp: FalconBoard/FalconBoard.h \
		FalconBoard/snipper.h \
		FalconBoard/pencolorsdialog.h \
		FalconBoard/common.h \
		Debug/Ui/ui_pencolorsdialog.h \
		Debug/Ui/ui_FalconBoard.h \
		FalconBoard/DrawArea.h \
		FalconBoard/drawables.h \
		FalconBoard/config.h \
		FalconBoard/quadtree.h \
		FalconBoard/history.h \
		FalconBoard/pagesetup.h \
		Debug/Ui/ui_pagesetup.h \
		FalconBoard/myprinter.h \
		FalconBoard/myevent.h \
		Debug/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /win/d/sajat/vegyes/FalconBoard/Debug/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/win/d/sajat/vegyes/FalconBoard/FalconBoard -I/win/d/sajat/vegyes/FalconBoard/FalconBoard -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include FalconBoard/FalconBoard.h -o Debug/moc/moc_FalconBoard.cpp

Debug/moc/moc_helpdialog.cpp: FalconBoard/helpdialog.h \
		Debug/Ui/ui_helpdialog.h \
		Debug/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /win/d/sajat/vegyes/FalconBoard/Debug/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/win/d/sajat/vegyes/FalconBoard/FalconBoard -I/win/d/sajat/vegyes/FalconBoard/FalconBoard -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include FalconBoard/helpdialog.h -o Debug/moc/moc_helpdialog.cpp

Debug/moc/moc_pagesetup.cpp: FalconBoard/pagesetup.h \
		Debug/Ui/ui_pagesetup.h \
		Debug/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /win/d/sajat/vegyes/FalconBoard/Debug/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/win/d/sajat/vegyes/FalconBoard/FalconBoard -I/win/d/sajat/vegyes/FalconBoard/FalconBoard -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include FalconBoard/pagesetup.h -o Debug/moc/moc_pagesetup.cpp

Debug/moc/moc_pencolorsdialog.cpp: FalconBoard/pencolorsdialog.h \
		FalconBoard/common.h \
		Debug/Ui/ui_pencolorsdialog.h \
		Debug/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /win/d/sajat/vegyes/FalconBoard/Debug/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/win/d/sajat/vegyes/FalconBoard/FalconBoard -I/win/d/sajat/vegyes/FalconBoard/FalconBoard -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include FalconBoard/pencolorsdialog.h -o Debug/moc/moc_pencolorsdialog.cpp

Debug/moc/moc_pencolorset.cpp: FalconBoard/pencolorset.h \
		FalconBoard/config.h \
		FalconBoard/common.h \
		Debug/Ui/ui_pencolorset.h \
		Debug/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /win/d/sajat/vegyes/FalconBoard/Debug/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/win/d/sajat/vegyes/FalconBoard/FalconBoard -I/win/d/sajat/vegyes/FalconBoard/FalconBoard -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include FalconBoard/pencolorset.h -o Debug/moc/moc_pencolorset.cpp

Debug/moc/moc_printprogress.cpp: FalconBoard/printprogress.h \
		Debug/Ui/ui_printprogress.h \
		Debug/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /win/d/sajat/vegyes/FalconBoard/Debug/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/win/d/sajat/vegyes/FalconBoard/FalconBoard -I/win/d/sajat/vegyes/FalconBoard/FalconBoard -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include FalconBoard/printprogress.h -o Debug/moc/moc_printprogress.cpp

Debug/moc/moc_rotateinput.cpp: FalconBoard/rotateinput.h \
		Debug/Ui/ui_rotateinput.h \
		Debug/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /win/d/sajat/vegyes/FalconBoard/Debug/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/win/d/sajat/vegyes/FalconBoard/FalconBoard -I/win/d/sajat/vegyes/FalconBoard/FalconBoard -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include FalconBoard/rotateinput.h -o Debug/moc/moc_rotateinput.cpp

Debug/moc/moc_screenshotTransparency.cpp: FalconBoard/screenshotTransparency.h \
		Debug/Ui/ui_screenshotTransparency.h \
		Debug/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /win/d/sajat/vegyes/FalconBoard/Debug/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/win/d/sajat/vegyes/FalconBoard/FalconBoard -I/win/d/sajat/vegyes/FalconBoard/FalconBoard -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include FalconBoard/screenshotTransparency.h -o Debug/moc/moc_screenshotTransparency.cpp

Debug/moc/moc_snipper.cpp: FalconBoard/snipper.h \
		Debug/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /win/d/sajat/vegyes/FalconBoard/Debug/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/win/d/sajat/vegyes/FalconBoard/FalconBoard -I/win/d/sajat/vegyes/FalconBoard/FalconBoard -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include FalconBoard/snipper.h -o Debug/moc/moc_snipper.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: Debug/Ui/ui_FalconBoard.h Debug/Ui/ui_helpdialog.h Debug/Ui/ui_pagesetup.h Debug/Ui/ui_pencolorsdialog.h Debug/Ui/ui_pencolorset.h Debug/Ui/ui_printprogress.h Debug/Ui/ui_rotateinput.h Debug/Ui/ui_screenshotTransparency.h
compiler_uic_clean:
	-$(DEL_FILE) Debug/Ui/ui_FalconBoard.h Debug/Ui/ui_helpdialog.h Debug/Ui/ui_pagesetup.h Debug/Ui/ui_pencolorsdialog.h Debug/Ui/ui_pencolorset.h Debug/Ui/ui_printprogress.h Debug/Ui/ui_rotateinput.h Debug/Ui/ui_screenshotTransparency.h
Debug/Ui/ui_FalconBoard.h: FalconBoard/FalconBoard.ui \
		/usr/lib/qt5/bin/uic \
		FalconBoard/DrawArea.h \
		FalconBoard/common.h \
		FalconBoard/drawables.h \
		FalconBoard/config.h \
		FalconBoard/quadtree.h \
		FalconBoard/history.h \
		FalconBoard/pagesetup.h \
		Debug/Ui/ui_pagesetup.h \
		FalconBoard/myprinter.h \
		FalconBoard/myevent.h
	/usr/lib/qt5/bin/uic FalconBoard/FalconBoard.ui -o Debug/Ui/ui_FalconBoard.h

Debug/Ui/ui_helpdialog.h: FalconBoard/helpdialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic FalconBoard/helpdialog.ui -o Debug/Ui/ui_helpdialog.h

Debug/Ui/ui_pagesetup.h: FalconBoard/pagesetup.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic FalconBoard/pagesetup.ui -o Debug/Ui/ui_pagesetup.h

Debug/Ui/ui_pencolorsdialog.h: FalconBoard/pencolorsdialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic FalconBoard/pencolorsdialog.ui -o Debug/Ui/ui_pencolorsdialog.h

Debug/Ui/ui_pencolorset.h: FalconBoard/pencolorset.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic FalconBoard/pencolorset.ui -o Debug/Ui/ui_pencolorset.h

Debug/Ui/ui_printprogress.h: FalconBoard/printprogress.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic FalconBoard/printprogress.ui -o Debug/Ui/ui_printprogress.h

Debug/Ui/ui_rotateinput.h: FalconBoard/rotateinput.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic FalconBoard/rotateinput.ui -o Debug/Ui/ui_rotateinput.h

Debug/Ui/ui_screenshotTransparency.h: FalconBoard/screenshotTransparency.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic FalconBoard/screenshotTransparency.ui -o Debug/Ui/ui_screenshotTransparency.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

Debug/common.o: FalconBoard/common.cpp FalconBoard/common.h \
		FalconBoard/config.h \
		FalconBoard/drawables.h \
		FalconBoard/quadtree.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Debug/common.o FalconBoard/common.cpp

Debug/drawables.o: FalconBoard/drawables.cpp FalconBoard/drawables.h \
		FalconBoard/config.h \
		FalconBoard/common.h \
		FalconBoard/quadtree.h \
		FalconBoard/history.h \
		FalconBoard/pagesetup.h \
		Debug/Ui/ui_pagesetup.h \
		FalconBoard/smoother.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Debug/drawables.o FalconBoard/drawables.cpp

Debug/DrawArea.o: FalconBoard/DrawArea.cpp FalconBoard/config.h \
		FalconBoard/common.h \
		FalconBoard/rotateinput.h \
		Debug/Ui/ui_rotateinput.h \
		FalconBoard/DrawArea.h \
		FalconBoard/drawables.h \
		FalconBoard/quadtree.h \
		FalconBoard/history.h \
		FalconBoard/pagesetup.h \
		Debug/Ui/ui_pagesetup.h \
		FalconBoard/myprinter.h \
		FalconBoard/myevent.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Debug/DrawArea.o FalconBoard/DrawArea.cpp

Debug/FalconBoard.o: FalconBoard/FalconBoard.cpp FalconBoard/config.h \
		FalconBoard/pagesetup.h \
		Debug/Ui/ui_pagesetup.h \
		FalconBoard/common.h \
		FalconBoard/DrawArea.h \
		FalconBoard/drawables.h \
		FalconBoard/quadtree.h \
		FalconBoard/history.h \
		FalconBoard/myprinter.h \
		FalconBoard/myevent.h \
		FalconBoard/screenshotTransparency.h \
		Debug/Ui/ui_screenshotTransparency.h \
		FalconBoard/FalconBoard.h \
		FalconBoard/snipper.h \
		FalconBoard/pencolorsdialog.h \
		Debug/Ui/ui_pencolorsdialog.h \
		Debug/Ui/ui_FalconBoard.h \
		FalconBoard/helpdialog.h \
		Debug/Ui/ui_helpdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Debug/FalconBoard.o FalconBoard/FalconBoard.cpp

Debug/history.o: FalconBoard/history.cpp FalconBoard/config.h \
		FalconBoard/history.h \
		FalconBoard/pagesetup.h \
		Debug/Ui/ui_pagesetup.h \
		FalconBoard/drawables.h \
		FalconBoard/common.h \
		FalconBoard/quadtree.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Debug/history.o FalconBoard/history.cpp

Debug/main.o: FalconBoard/main.cpp FalconBoard/common.h \
		FalconBoard/FalconBoard.h \
		FalconBoard/snipper.h \
		FalconBoard/pencolorsdialog.h \
		Debug/Ui/ui_pencolorsdialog.h \
		Debug/Ui/ui_FalconBoard.h \
		FalconBoard/DrawArea.h \
		FalconBoard/drawables.h \
		FalconBoard/config.h \
		FalconBoard/quadtree.h \
		FalconBoard/history.h \
		FalconBoard/pagesetup.h \
		Debug/Ui/ui_pagesetup.h \
		FalconBoard/myprinter.h \
		FalconBoard/myevent.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Debug/main.o FalconBoard/main.cpp

Debug/myprinter.o: FalconBoard/myprinter.cpp FalconBoard/config.h \
		FalconBoard/history.h \
		FalconBoard/pagesetup.h \
		Debug/Ui/ui_pagesetup.h \
		FalconBoard/drawables.h \
		FalconBoard/common.h \
		FalconBoard/quadtree.h \
		FalconBoard/printprogress.h \
		Debug/Ui/ui_printprogress.h \
		FalconBoard/myprinter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Debug/myprinter.o FalconBoard/myprinter.cpp

Debug/pagesetup.o: FalconBoard/pagesetup.cpp FalconBoard/config.h \
		FalconBoard/common.h \
		FalconBoard/pagesetup.h \
		Debug/Ui/ui_pagesetup.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Debug/pagesetup.o FalconBoard/pagesetup.cpp

Debug/pencolorsdialog.o: FalconBoard/pencolorsdialog.cpp FalconBoard/config.h \
		FalconBoard/pencolorsdialog.h \
		FalconBoard/common.h \
		Debug/Ui/ui_pencolorsdialog.h \
		FalconBoard/pencolorset.h \
		Debug/Ui/ui_pencolorset.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Debug/pencolorsdialog.o FalconBoard/pencolorsdialog.cpp

Debug/pencolorset.o: FalconBoard/pencolorset.cpp FalconBoard/pencolorset.h \
		FalconBoard/config.h \
		FalconBoard/common.h \
		Debug/Ui/ui_pencolorset.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Debug/pencolorset.o FalconBoard/pencolorset.cpp

Debug/rotateinput.o: FalconBoard/rotateinput.cpp FalconBoard/rotateinput.h \
		Debug/Ui/ui_rotateinput.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Debug/rotateinput.o FalconBoard/rotateinput.cpp

Debug/screenshotTransparency.o: FalconBoard/screenshotTransparency.cpp FalconBoard/screenshotTransparency.h \
		Debug/Ui/ui_screenshotTransparency.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Debug/screenshotTransparency.o FalconBoard/screenshotTransparency.cpp

Debug/snipper.o: FalconBoard/snipper.cpp FalconBoard/snipper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Debug/snipper.o FalconBoard/snipper.cpp

Debug/qrc_FalconBoard.o: Debug/rcc/qrc_FalconBoard.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Debug/qrc_FalconBoard.o Debug/rcc/qrc_FalconBoard.cpp

Debug/moc_DrawArea.o: Debug/moc/moc_DrawArea.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Debug/moc_DrawArea.o Debug/moc/moc_DrawArea.cpp

Debug/moc_FalconBoard.o: Debug/moc/moc_FalconBoard.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Debug/moc_FalconBoard.o Debug/moc/moc_FalconBoard.cpp

Debug/moc_helpdialog.o: Debug/moc/moc_helpdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Debug/moc_helpdialog.o Debug/moc/moc_helpdialog.cpp

Debug/moc_pagesetup.o: Debug/moc/moc_pagesetup.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Debug/moc_pagesetup.o Debug/moc/moc_pagesetup.cpp

Debug/moc_pencolorsdialog.o: Debug/moc/moc_pencolorsdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Debug/moc_pencolorsdialog.o Debug/moc/moc_pencolorsdialog.cpp

Debug/moc_pencolorset.o: Debug/moc/moc_pencolorset.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Debug/moc_pencolorset.o Debug/moc/moc_pencolorset.cpp

Debug/moc_printprogress.o: Debug/moc/moc_printprogress.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Debug/moc_printprogress.o Debug/moc/moc_printprogress.cpp

Debug/moc_rotateinput.o: Debug/moc/moc_rotateinput.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Debug/moc_rotateinput.o Debug/moc/moc_rotateinput.cpp

Debug/moc_screenshotTransparency.o: Debug/moc/moc_screenshotTransparency.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Debug/moc_screenshotTransparency.o Debug/moc/moc_screenshotTransparency.cpp

Debug/moc_snipper.o: Debug/moc/moc_snipper.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Debug/moc_snipper.o Debug/moc/moc_snipper.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

