# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = subdirs
SUBDIRS = MyWhiteBoard\
          MyWhiteboardViewer
TARGET = MyWhiteboard
DESTDIR = ../Debug
CONFIG += debug
LIBS += -L"."
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .
include(MyWhiteboard.pri)
win32:RC_FILE = MyWhiteboard.rc
